# Generated by Django 4.2.13 on 2024-05-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclass', models.SmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('age', models.FloatField()),
                ('sibsp', models.SmallIntegerField()),
                ('parch', models.SmallIntegerField()),
                ('ticket', models.CharField(max_length=18)),
                ('fare', models.FloatField()),
                ('cabin', models.CharField(max_length=15)),
                ('embarked', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PredictorsResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictor', models.CharField(max_length=43)),
                ('cross_val_score', models.FloatField()),
                ('accuracy_score', models.FloatField()),
                ('best_estimators', models.CharField(max_length=227)),
                ('features', models.CharField(max_length=281)),
            ],
        ),
    ]
